from creation import *
from common.unit import *
from uncommon.unit import *

luffy_special = Special('luffy_special', luffy_common, luffy_common, luffy_common)
nami_special = Special('nami_special', nami_common, nami_common, nami_common)
sanji_special = Special('sanji_special', sanji_common, sanji_common, sanji_common)
zoro_special = Special('zoro_special', zoro_common, zoro_common, zoro_common)
buggy_special = Special('buggy_special', buggy_common, buggy_common, buggy_common)
robin_special = Special('robin_special', robin_uncommon, robin_uncommon, chopper_common)
marco_special = Special('marco_special', blueno_uncommon, ace_uncommon, sanji_common)
chaka_special = Special('chaka_special', blueno_uncommon, fukuro_uncommon, chopper_common)
rob_lucci_special = Special('rob_lucci_special', fukuro_uncommon, robin_uncommon, luffy_common)
capone_special = Special('capone_special', fukuro_uncommon, gunman_common, buggy_common)
law_special = Special('law_special', bepo_uncommon, tashigi_uncommon, buggy_common)
kuma_special = Special('kuma_special', bepo_uncommon, franky_uncommon, zoro_common)
xdrake_special = Special('xdrake_special', tashigi_uncommon, fukuro_uncommon, chopper_common)
killer_special = Special('killer_special', tashigi_uncommon, brook_uncommon, buggy_common)
smoker_special = Special('smoker_special', gunman_common, tashigi_uncommon, swordsman_common)
bon_clay_special = Special('bon_clay_special', inazuma_uncommon, robin_uncommon, nami_common)
inazuma_special = SpecialDoubleClass('inazuma_special', inazuma_uncommon, inazuma_uncommon)
franky_special = Special('franky_special', franky_uncommon, franky_uncommon, zoro_common)
crocodile_special = Special('crocodile_special', franky_uncommon, sogeking_uncommon, buggy_common)
moria_special = Special('moria_special', brook_uncommon, brook_uncommon, sanji_common)
helmeppo_special = Special('helmeppo_special', brook_uncommon, zoro_common, sanji_common)
ace_special = Special('ace_special', ace_uncommon, ace_uncommon, usopp_common)
jinbe_special = Special('jinbe_special', ace_uncommon, fukuro_uncommon, buggy_special)
arlong_special = Special('arlong_special', hatchan_uncommon, hatchan_uncommon, luffy_common)
kuro_special = Special('kuro_special', hatchan_uncommon, swordsman_common, zoro_common)
squard_special = Special('squard_special', chopper_uncommon, franky_uncommon, nami_common)
chopper_rumble_special = Special('chopper_rumble_special', chopper_uncommon, inazuma_uncommon, swordsman_common)
chopper_brain_special = Special('chopper_brain_special', chopper_uncommon, robin_uncommon, buggy_common)
basil_hawkin_special = Special('basil_hawkin_special', perona_uncommon, blueno_uncommon, usopp_common)
kid_special = Special('kid_special', perona_uncommon, bepo_uncommon, buggy_common)
enel_special = Special('enel_special', sogeking_uncommon, bepo_uncommon, sanji_common)
usopp_flame_special = SpecialDoubleClass('usopp_flame_special', sogeking_uncommon, sogeking_uncommon)
absalom_special = SpecialQuadClass('absalom_special', zombie_uncommon, zombie_uncommon, zombie_uncommon, nami_common)

