from creation import *
from common.unit import *
from uncommon.unit import *
from special.unit import *
from rare.unit import *

moria_legendary = Legendary('moria_legendary',oars_rare, ryuma_rare, sugar_rare)
luffy_nightmare_legendary = LegendaryQuad('luffy_nightmare_legendary', oars_rare, ryuma_rare, absalom_special, luffy_rare)
jinbe_legendary = Legendary('jinbe_legendary', vander_decken_rare, law_rare, akainu_rare)
smoker_legendary = Legendary('smoker_legendary', garp_rare, magellan_rare, momonga_rare)
dragon_legendary = Legendary('dragon_legendary', ivankov_rare, sabo_rare, vivi_rare)
boa_hancock_legendary = Legendary('boa_hancock_legendary', boa_hancock_rare, mihawk_rare, sanji_rare)
shiki_legendary = Legendary('shiki_legendary', wyper_rare, kaku_rare, magellan_rare)
sengoku_legendary = Legendary('sengoku_legendary', akainu_rare, aokiji_rare, kizaru_rare)
shanks_legendary = Legendary('shanks_legendary', shanks_rare, ben_beckman_rare, sanji_rare)
whitebeard_legendary = Legendary('whitebeard_legendary', diamond_jozu_rare, marco_rare, kinemon_rare)
reiju_legendary = Legendary('reiju_legendary', magellan_rare, crocodile_rare, baby_5_rare)
calgara_legendary = Legendary('calgara_legendary', usopp_rare, wyper_rare, brook_rare)
laboon_legendary = Legendary('laboon_legendary', brook_rare, bartolomeo_rare, shiryu_rare)
bartolomeo_legendary = Legendary('bartolomeo_legendary', bartolomeo_rare, luffy_rare, usopp_rare)
zoro_legendary = Legendary('zoro_legendary', zoro_rare, perona_rare, mihawk_rare)
lucci_legendary = Legendary('lucci_legendary', kaku_rare, law_rare, garp_rare)
sanji_legendary = Legendary('sanji_legendary', sanji_rare, ivankov_rare, basil_hawkin_rare)
koby_legendary = Legendary('koby_legendary', shiryu_rare, zeff_rare, shanks_rare)
fujitora_legendary = Legendary('fujitora_legendary', kinemon_rare, crocodile_rare, doflamingo_rare)
sugar_legendary = Legendary('sugar_legendary', sugar_rare, basil_hawkin_rare, usopp_rare)
luffy_jet_legendary = Legendary('luffy_jet_legendary', luffy_rare, kaku_rare, xdrake_rare)
toki_legendary = Legendary('toki_legendary', kizaru_rare, zoro_rare, ancient_ship_rare)
marco_legendary = Legendary('marco_legendary', marco_rare, boa_hancock_rare, baby_5_rare)
ulti_legendary = Legendary('ulti_legendary', chopper_horn_point_rare, ben_beckman_rare, sentomaru_rare)
dr_hiriluk_legendary = Legendary('dr_hiriluk_legendary', chopper_horn_point_rare, burgess_rare, vander_decken_rare)
nekomamushi_legendary = Legendary('nekomamushi_legendary', kid_rare, wyper_rare, xdrake_rare)
law_legendary = Legendary('law_legendary', law_rare, kid_rare, sentomaru_rare)
ace_legendary = Legendary('ace_legendary', marco_rare, momonga_rare, blackbeard_rare)
z_legendary = Legendary('z_legendary', burgess_rare, aokiji_rare, sabo_rare)
caeser_clown_legendary = Legendary('caeser_clown_legendary', doflamingo_rare, kizaru_rare, garp_rare)
nami_legendary = Legendary('nami_legendary', vivi_rare, brook_rare, perona_rare)
blackbeard_legendary = Legendary('blackbeard_legendary', blackbeard_rare, shiryu_rare, burgess_rare)
kuma_legendary = Legendary('kuma_legendary', sentomaru_rare, baby_5_rare, chopper_horn_point_rare)
cracker_legendary = Legendary('cracker_legendary', zeff_rare, sugar_rare, kinemon_rare)
shinobu_legendary = Legendary('shinobu_legendary', ryuma_rare, blackbeard_rare, kinemon_rare)
king_legendary = Legendary('king_legendary', xdrake_rare, basil_hawkin_rare, doflamingo_rare)
rayleigh_legendary = Legendary('rayleigh_legendary', rayleigh_hidden_rare, sentomaru_rare, jinbe_special)
pirate_ship = HiddenRandom('pirate_ship')
expansion_pack = HiddenRandom('expansion_pack')
zombie_general = HiddenRandom('zombie_general')
