import sys
sys.path.append('../Noob Folder')
from creation import *
from common.unit import *
from uncommon.unit import *
from special.unit import *

ancient_ship_rare = HiddenRandom('ancient_ship_rare')
rayleigh_hidden_rare = HiddenRandom('rayleigh_hidden_rare')

luffy_rare = Rare('luffy_rare', luffy_special, enel_special, bon_clay_special)
sanji_rare = Rare('sanji_rare', sanji_special, chopper_rumble_special, kid_special)
zoro_rare = Rare('zoro_rare', zoro_special, moria_special, smoker_special)
mihawk_rare = Rare('mihawk_rare', zoro_special, kuro_special, xdrake_special)
boa_hancock_rare = Rare('boa_hancock_rare', nami_special, arlong_special, luffy_special)
crocodile_rare = Rare('crocodile_rare', crocodile_special, jinbe_special, bon_clay_special)
vivi_rare = Rare('vivi_rare', chaka_special, crocodile_special, nami_special)
baby_5_rare = Rare('baby_5_rare', franky_special, kuma_special, rob_lucci_special)
sentomaru_rare = Rare('sentomaru_rare', kuma_special, chopper_brain_special, capone_special)
garp_rare = Rare('garp_rare', smoker_special, luffy_special, xdrake_special)
magellan_rare = Rare('magellan_rare', jinbe_special, ace_special, buggy_special)
momonga_rare = Rare('momonga_rare', jinbe_special, smoker_special, helmeppo_special)
blackbeard_rare = Rare('blackbeard_rare', ace_special, squard_special, xdrake_special)
akainu_rare = Rare('akainu_rare', ace_special, inazuma_special, crocodile_special)
aokiji_rare = Rare('aokiji_rare', robin_special, enel_special, squard_special)
kizaru_rare = Rare('kizaru_rare', helmeppo_special, law_special, kid_special)
kaku_rare = Rare('kaku_rare', rob_lucci_special, chaka_special, robin_special)
law_rare = Rare('law_rare', law_special, chopper_brain_special, franky_special)
burgess_rare = Rare('burgess_rare', basil_hawkin_special, marco_special, buggy_special)
basil_hawkin_rare = Rare('basil_hawkin_rare', basil_hawkin_special, law_special, killer_special)
oars_rare = Rare('oars_rare', moria_special, moria_special, luffy_special)
ryuma_rare = RarePenClass('ryuma_rare', moria_special, zoro_common, sogeking_uncommon, perona_uncommon, swordsman_common)
perona_rare = RareQuadClass('perona_rare', absalom_special, perona_uncommon, chopper_brain_special, sanji_special)
sugar_rare = RareQuadClass('sugar_rare', chopper_brain_special, zoro_special, perona_uncommon, usopp_common)
brook_rare = Rare('brook_rare', brook_uncommon, moria_special, rob_lucci_special)
doflamingo_rare = Rare('doflamingo_rare', chopper_rumble_special, rob_lucci_special, buggy_special)
chopper_horn_point_rare = Rare('chopper_horn_point_rare', chopper_rumble_special, helmeppo_special, law_special)
shanks_rare = Rare('shanks_rare', buggy_special, usopp_flame_special, luffy_special)
ben_beckman_rare = Rare('ben_beckman_rare', usopp_flame_special, smoker_special, enel_special)
usopp_rare = Rare('usopp_rare', usopp_flame_special, capone_special, nami_special)
ivankov_rare = Rare('ivankov_rare', inazuma_special, robin_special, crocodile_special)
sabo_rare = Rare('sabo_rare', inazuma_special, kuma_special, marco_special)
marco_rare = Rare('marco_rare', marco_special, chopper_rumble_special, chaka_special)
diamond_jozu_rare = Rare('diamond_jozu_rare', squard_special, capone_special, kuro_special)
bartolomeo_rare = Rare('bartolomeo_rare', kuro_special, arlong_special, franky_special)
vander_decken_rare = Rare('vander_decken_rare', arlong_special, jinbe_special, helmeppo_special)
wyper_rare = Rare('wyper_rare', enel_special, usopp_flame_special, sanji_special)
zeff_rare = Rare('zeff_rare', bon_clay_special, inazuma_special, basil_hawkin_special)
kid_rare = Rare('kid_rare', kid_special, nami_special, killer_special)
kinemon_rare = Rare('kinemon_rare', killer_special, kuro_special, ace_special)
shiryu_rare = Rare('shiryu_rare', capone_special, xdrake_special, sanji_special)
xdrake_rare = Rare('xdrake_rare', xdrake_special, basil_hawkin_special, arlong_special)
